// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymvqbhenfnemktxemuko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdnFiaGVuZm5lbWt0eGVtdWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODA3MjEsImV4cCI6MjA1OTk1NjcyMX0.nPnkIW42L52uqVDAjImHl4A28JKra6CTKwigpso_yIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);